<a href="https://colab.research.google.com/github/HiteshGourana/AWS-ML/blob/main/day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
data = {
    "experience":[1,2,3,4,5,6,7,8,9,10],
    "salary":[100,200,300,400,500,600,700,800,900,1000]
}
# data frame
df = pd.DataFrame(data)
# print(df)

# head -> starting 5 rows
print(df.head())

# head -> starting 2 rows
print(df.head(2))

# head -> negative
print(df.head(-3))

   experience  salary
0           1     100
1           2     200
2           3     300
3           4     400
4           5     500
   experience  salary
0           1     100
1           2     200
   experience  salary
0           1     100
1           2     200
2           3     300
3           4     400
4           5     500
5           6     600
6           7     700

In [2]:
print(df.tail())

   experience  salary
5           6     600
6           7     700
7           8     800
8           9     900
9          10    1000

In [3]:
print(df.tail(2))

   experience  salary
8           9     900
9          10    1000

In [4]:
import numpy as np
data = {
    "experience":[1,2,3,4,5,6,7,8,9,np.nan],
    "salary":[np.nan,200,300,400,np.nan,600,700,800,900,1000]
}

df = pd.DataFrame(data)

# info
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   experience  9 non-null      float64
 1   salary      8 non-null      float64
dtypes: float64(2)
memory usage: 292.0 bytes
None

In [5]:
import pandas as pd

data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}

In [6]:
# operations on columns
import pandas as pd
data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}
df = pd.DataFrame(data)

# select cols
print(df['Emp_ID'])

# select col store in variable
abc = df['Emp_ID']
print(abc)

0    101
1    102
2    103
3    104
4    105
5    106
Name: Emp_ID, dtype: int64
0    101
1    102
2    103
3    104
4    105
5    106
Name: Emp_ID, dtype: int64

In [7]:
# operations on columns
import pandas as pd
data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}
df = pd.DataFrame(data)

# drop cols
df.drop("Emp_ID",axis=1,inplace=True)
print(df)

# drop multi cols
df.drop(["Name","Department"],axis=1,inplace=True)
print(df)

   Name Department  Salary  Experience
0  Amit         IT   50000           2
1  Riya         HR   45000           3
2   Raj    Finance   60000           5
3  Sara         IT   55000           4
4  John      Sales   48000           1
5  Neha         HR   52000           3
   Salary  Experience
0   50000           2
1   45000           3
2   60000           5
3   55000           4
4   48000           1
5   52000           3

In [8]:
import pandas as pd
data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}
df = pd.DataFrame(data)
print(df)

# multi rows and cols
print(df.iloc[[0,1],[0,1]])

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
   Emp_ID  Name
0     101  Amit
1     102  Riya

In [9]:
df=pd.read_json("https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json")
df.head()

      name  gender  physics  maths  english
0     arun    Male       88     87       78
1   rajesh    Male       96    100       95
2  moorthy    Male       89     90       70
3     raja    Male       30     25       40
4     usha  Female       67     45       78

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     14 non-null     object
 1   gender   14 non-null     object
 2   physics  14 non-null     int64
 3   maths    14 non-null     int64
 4   english  14 non-null     int64
dtypes: int64(3), object(2)
memory usage: 692.0+ bytes

In [11]:
df.describe()

          physics       maths     english
count   14.000000   14.000000   14.000000
mean    65.857143   71.285714   69.857143
std     26.046872   24.237379   21.205432
min     12.000000   25.000000   23.000000
25%     56.000000   48.250000   67.000000
50%     69.000000   79.000000   74.000000
75%     85.500000   89.750000   78.000000
max    100.000000  100.000000  100.000000

In [12]:
df.shape

(14, 5)

In [13]:
df.columns

Index(['name', 'gender', 'physics', 'maths', 'english'], dtype='object')

In [15]:
df.isnull().sum()

name       0
gender     0
physics    0
maths      0
english    0
dtype: int64

physics
78     2
56     2
67     2
89     1
96     1
88     1
30     1
12     1
71     1
100    1
34     1
Name: count, dtype: int64

In [18]:

print(df.head())
print(df.info())
print(df.describe())
print(df.isnull().sum())
print(df.duplicated().sum())

def grade(x):
    if x >= 90:
        return "A+"
    elif x >= 80:
        return "A"
    elif x >= 70:
        return "B"
    elif x >= 60:
        return "C"
    elif x >= 50:
        return "D"
    else:
        return "F"

df["Grade"] = df["Average"].apply(grade)

print(df.sort_values("Rank"))

      name  gender  physics  maths  english  Total    Average  Rank Result  \
0     arun    Male       88     87       78    253  84.333333   3.0   Pass
1   rajesh    Male       96    100       95    291  97.000000   2.0   Pass
2  moorthy    Male       89     90       70    249  83.000000   4.0   Pass
3     raja    Male       30     25       40     95  31.666667  13.0   Fail
4     usha  Female       67     45       78    190  63.333333   8.0   Pass

  Grade
0     A
1    A+
2     A
3     F
4     C
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     14 non-null     object
 1   gender   14 non-null     object
 2   physics  14 non-null     int64
 3   maths    14 non-null     int64
 4   english  14 non-null     int64
 5   Total    14 non-null     int64
 6   Average  14 non-null     float64
 7   Rank     14 non-null     float64
 8   Result   14 non-null     object
 9   Grade    14 non-null     object
dtypes: float64(2), int64(4), object(4)
memory usage: 1.2+ KB
None
          physics       maths     english       Total     Average       Rank
count   14.000000   14.000000   14.000000   14.000000   14.000000  14.000000
mean    65.857143   71.285714   69.857143  207.000000   69.000000   7.214286
std     26.046872   24.237379   21.205432   56.301387   18.767129   3.826599
min     12.000000   25.000000   23.000000   95.000000   31.666667   1.000000
25%     56.000000   48.250000   67.000000  180.000000   60.000000   4.250000
50%     69.000000   79.000000   74.000000  195.500000   65.166667   7.500000
75%     85.500000   89.750000   78.000000  248.000000   82.666667  10.000000
max    100.000000  100.000000  100.000000  300.000000  100.000000  13.000000
name       0
gender     0
physics    0
maths      0
english    0
Total      0
Average    0
Rank       0
Result     0
Grade      0
dtype: int64
0
       name  gender  physics  maths  english  Total     Average  Rank Result  \
10    Gowri  Female      100    100      100    300  100.000000   1.0   Pass
1    rajesh    Male       96    100       95    291   97.000000   2.0   Pass
0      arun    Male       88     87       78    253   84.333333   3.0   Pass
2   moorthy    Male       89     90       70    249   83.000000   4.0   Pass
13  Jenifer  Female       67     88       90    245   81.666667   5.0   Pass
7   Kavitha  Female       78     71       67    216   72.000000   6.0   Pass
12  Murugan    Male       34     89       78    201   67.000000   7.0   Pass
4      usha  Female       67     45       78    190   63.333333   8.0   Pass
9      Hema  Female       71     90       23    184   61.333333   9.0   Pass
11      Ram    Male       78     55       47    180   60.000000  10.0   Pass
5     priya  Female       56     46       78    180   60.000000  10.0   Pass
8    Dinesh    Male       56     45       67    168   56.000000  11.0   Pass
6    Sundar    Male       12     67       67    146   48.666667  12.0   Pass
3      raja    Male       30     25       40     95   31.666667  13.0   Fail

   Grade
10    A+
1     A+
0      A
2      A
13     A
7      B
12     C
4      C
9      C
11     C
5      C
8      D
6      F
3      F